### ISSUE TITLE
Sensor example not working

### ISSUE THREAD

**Issue by phanirithvij** [codeanticode/processing-android-tutorials#6]
I've made a sketch following the sensor example from the [docs](https://android.processing.org/tutorials/sensors/index.html)

The app crashed when used as a live wallpaper but it works when used as a regular app.

The error was
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
 at processing.test.test_android_sketch.test_android_sketch.setup(test_android_sketch.java:55)
 at processing.core.PApplet.handleDraw(PApplet.java:1838)
 at processing.opengl.PSurfaceGLES$RendererGLES.onDrawFrame(PSurfaceGLES.java:264)
 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
```

The 55th line it mentions is
```java
void setup(){
  ...
  manager = (SensorManager)context.getSystemService(Context.SENSOR_SERVICE);
  ...
}
```
The app works normally. But the live wallpaper doesn't.

**Comment by phanirithvij** [comment]
So context cannot be accessed when using as a live wallpaper?
I don't think that's the case as I saw many live wallpapers which use sensors to show parallax backgrounds.

What am I missing here?

**Comment by phanirithvij** [comment]
So I found the mistake.
The docs use the below method in line 26
```java
    context = getActivity();
```
It should actually be 

```java
    context = getContext();
```
I wonder how the app even worked.
